### ISSUE TITLE
[Question] Does it use default php float math or decimal math, when operating on floats?

### ISSUE THREAD

**Issue by diimpp** [chriskonnertz/string-calc#14]
Hi,

https://floating-point-gui.de/languages/php/

P.S. Cool grammar implementation :)

**Comment by chriskonnertz** [comment]
Hello,

basically it transforms a string into calls of PHP's internal operators, functions and constants. For example this is the addition: https://github.com/chriskonnertz/string-calc/blob/master/src/ChrisKonnertz/StringCalc/Symbols/Concrete/Operators/AdditionOperator.php

So the answer is: Default PHP math, no use of BC here. 

However, you should be able to add operators/function thatuse the BC extension.

**Comment by diimpp** [comment]
Thanks!
