### ISSUE TITLE
Modulo

### ISSUE THREAD

**Issue by simoheinonen** [chriskonnertz/string-calc#3]
https://en.wikipedia.org/wiki/Remainder

**Comment by simoheinonen** [comment]
See https://github.com/chriskonnertz/string-calc/blob/ed7dda7ec9f36b35eec22d2af6c7fbac620bb382/src/ChrisKonnertz/StringCalc/Symbols/Concrete/Functions/FModFunction.php

**Comment by simoheinonen** [comment]
Could have `%` as an alias to it though?

**Comment by chriskonnertz** [comment]
Hello,

seems to be legit!

**Comment by chriskonnertz** [comment]
Finally done: https://github.com/chriskonnertz/string-calc/releases/tag/v1.0.8

It is not an alias for fmod but PHP's `%` operator. This is consistent with the implementation of the other operators.

**Comment by simoheinonen** [comment]
Nice! Thanks!
